### ISSUE TITLE
Missing evaluate.py

### ISSUE THREAD

**Issue by arnabdeypolimi** [neuroethology/BKinD-3D#2]
The evaluation code mentioned in the readme is missing 
`python evaluation/evaluate.py --config config/H36M.yaml`

**Comment by lambdaloop** [comment]
Thank you for this issue. It seems we forgot to push our evaluation code.
I have pushed it now, it is here: https://github.com/neuroethology/BKinD-3D/blob/main/evaluation/evaluate.py 

Let us know if you have any issues running it!
